### ISSUE TITLE
Clarify pysm requirement

### ISSUE THREAD

**Issue by msyriac** [simonsobs/mapsims#22]
Has the mbs software stack switched to pysm 3? I get this error:
```
Traceback (most recent call last):
  File "bbcheck.py", line 6, in <module>
    import mapsims
  File "/global/homes/m/msyriac/repos/mapsims/mapsims/__init__.py", line 8, in <module>
    from .noise import SONoiseSimulator
  File "/global/homes/m/msyriac/repos/mapsims/mapsims/noise.py", line 6, in <module>
    import pysm.units as u
ModuleNotFoundError: No module named 'pysm.units'
```

If it has, the docs don't seem to have been updated to point to the location of pysm 3.

**Comment by zonca** [comment]
Yes,
I will update it after I deliver what is required for the TOD simulations.
For now either use a earlier release or install pysm3 from GitHub/healpy/pysm

**Comment by zonca** [comment]
https://mapsims.readthedocs.io/en/latest/installation.html

**Comment by zatkins2** [comment]
I still seem to be getting this issue:

```
In [1]: import pysm3

In [2]: pysm3.__version__
Out[2]: '3.3.2'

In [3]: import mapsims
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 import mapsims

File ~/repos/simonsobs/mapsims/mapsims/__init__.py:8, in <module>
      6 from ._astropy_init import *
      7 from .so_utils import Channel, SOChannel
----> 8 from .noise import SONoiseSimulator
      9 from .cmb import SOPrecomputedCMB, SOStandalonePrecomputedCMB
     10 from .runner import MapSim, from_config

File ~/repos/simonsobs/mapsims/mapsims/noise.py:7, in <module>
      4 from astropy.utils import data
      5 import warnings
----> 7 import pysm.units as u
      9 from so_models_v3 import SO_Noise_Calculator_Public_v3_1_1 as so_models
     10 from . import so_utils

ModuleNotFoundError: No module named 'pysm'
```

I installed `pysm3` from `conda-forge` but I had the same issue if I used `pip`. If you don't want to change the name in `mapsims` I think there's a way to backport the name `pysm` within the `pysm3` package so that `import pysm` also succeeds.
