### ISSUE TITLE
Error in running example

### ISSUE THREAD

**Issue by stevekchoi** [simonsobs/mapsims#41]
I wasn't sure if this was an appropriate thing to ask here, but in trying to run the exmaple toml file, I get the following error, which I am not sure how to fix...

```
stevekchoi@:~/work/build/mapsims$ mapsims_run mapsims/data/example_config_v0.2.toml 
//anaconda/envs/py36/lib/python3.6/site-packages/so_models_v3/SO_Noise_Calculator_Public_v3_1_1.py:217: RuntimeWarning: divide by zero encountered in double_scalars
  (self.Tatmos_C[i] * self.Tatmos_C[j])**.5) )
//anaconda/envs/py36/lib/python3.6/site-packages/so_pysm_models-2.1.dev661-py3.6.egg/so_pysm_models/utils/__init__.py:55: UserWarning: Retrieve data for dust_T_ns512.fits (if not cached already)
  warnings.warn(f"Retrieve data for {filename} (if not cached already)")
//anaconda/envs/py36/lib/python3.6/site-packages/so_pysm_models-2.1.dev661-py3.6.egg/so_pysm_models/utils/__init__.py:55: UserWarning: Retrieve data for dust_Q_ns512.fits (if not cached already)
  warnings.warn(f"Retrieve data for {filename} (if not cached already)")
//anaconda/envs/py36/lib/python3.6/site-packages/so_pysm_models-2.1.dev661-py3.6.egg/so_pysm_models/utils/__init__.py:55: UserWarning: Retrieve data for dust_U_ns512.fits (if not cached already)
  warnings.warn(f"Retrieve data for {filename} (if not cached already)")
Sigma is 0.000000 arcmin (0.000000 rad) 
-> fwhm is 0.000000 arcmin
Traceback (most recent call last):
  File "//anaconda/envs/py36/bin/mapsims_run", line 11, in <module>
    load_entry_point('mapsims==2.1.dev717', 'console_scripts', 'mapsims_run')()
  File "/Users/stevekchoi/work/build/mapsims/mapsims/runner.py", line 105, in command_line_script
    simulator.execute(write_outputs=True)
  File "/Users/stevekchoi/work/build/mapsims/mapsims/runner.py", line 350, in execute
    mpi_comm=COMM_WORLD,
  File "//anaconda/envs/py36/lib/python3.6/site-packages/pysm/models/template.py", line 121, in apply_smoothing_and_coord_transform
    smoothed_map = mpi.mpi_smoothing(input_map, fwhm, map_dist)
  File "//anaconda/envs/py36/lib/python3.6/site-packages/pysm/mpi.py", line 132, in mpi_smoothing
    map_dist.libsharp_grid,
AttributeError: 'MapDistribution' object has no attribute 'libsharp_grid'
```

**Comment by zonca** [comment]
thanks @stevekchoi, it looks like `libsharp` is missing, anyway you shouldn't need `libsharp` to run `mapsims`, I'll work on a fix and let you know when it is ready.

**Comment by stevekchoi** [comment]
hm... I am able to load with "import libsharp" in python. Do I need more?

**Comment by zonca** [comment]
have you installed PySM 3 from the conda package? if so can you test installing from the master branch from Github?

**Comment by stevekchoi** [comment]
I did use conda for it. I reinstalled it and get a different error:

`Traceback (most recent call last):
  File "//anaconda/envs/py36/lib/python3.6/site-packages/astropy/units/decorators.py", line 56, in _validate_arg_value
    is_equivalent = arg.unit.is_equivalent(allowed_unit,
AttributeError: 'numpy.ndarray' object has no attribute 'unit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda/envs/py36/bin/mapsims_run", line 11, in <module>
    load_entry_point('mapsims==2.1.dev717', 'console_scripts', 'mapsims_run')()
  File "/Users/stevekchoi/work/build/mapsims/mapsims/runner.py", line 105, in command_line_script
    simulator.execute(write_outputs=True)
  File "/Users/stevekchoi/work/build/mapsims/mapsims/runner.py", line 332, in execute
    *each.bandpass
  File "//anaconda/envs/py36/lib/python3.6/site-packages/pysm3-3.1.dev270-py3.6.egg/pysm/sky.py", line 114, in get_emission
    output += comp.get_emission(freq, weights=weights)
  File "//anaconda/envs/py36/lib/python3.6/site-packages/astropy/units/decorators.py", line 234, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)
  File "//anaconda/envs/py36/lib/python3.6/site-packages/so_pysm_models-2.1.dev661-py3.6.egg/so_pysm_models/alms.py", line 130, in get_emission
    u.uK_RJ, equivalencies=u.cmb_equivalencies(freqs)
  File "//anaconda/envs/py36/lib/python3.6/site-packages/astropy/units/decorators.py", line 230, in wrapper
    arg, valid_targets, self.equivalencies)
  File "//anaconda/envs/py36/lib/python3.6/site-packages/astropy/units/decorators.py", line 70, in _validate_arg_value
    .format(param_name, func_name, error_msg))
TypeError: Argument 'spec' to function 'cmb_equivalencies' has no 'unit' attribute. You may want to pass in an astropy Quantity `instead.``

**Comment by zonca** [comment]
ok, thanks, this error is due to my latest changes to PySM, I'll propagate those changes to `so_pysm_models` and let you know when it is fixed.

**Comment by zonca** [comment]
ok, I updated `so_pysm_models` and `mapsims` to the latest PySM,
all unit tests on Travis pass (using PySM master):

* https://travis-ci.org/github/simonsobs/so_pysm_models/builds/667517997
* https://travis-ci.org/github/simonsobs/mapsims/builds/667518968

so you should update them to the latest commits on master.

Next week at most I'll package a new conda package for PySM.

**Comment by stevekchoi** [comment]
back to the same libsharp error...

Sigma is 0.000000 arcmin (0.000000 rad) 
-> fwhm is 0.000000 arcmin
Traceback (most recent call last):
  File "//anaconda/envs/py36/bin/mapsims_run", line 11, in <module>
    load_entry_point('mapsims==2.1.dev718', 'console_scripts', 'mapsims_run')()
  File "/Users/stevekchoi/work/build/mapsims/mapsims/runner.py", line 102, in command_line_script
    simulator.execute(write_outputs=True)
  File "/Users/stevekchoi/work/build/mapsims/mapsims/runner.py", line 349, in execute
    mpi_comm=COMM_WORLD,
  File "//anaconda/envs/py36/lib/python3.6/site-packages/pysm3-3.1.dev270-py3.6.egg/pysm/models/template.py", line 149, in apply_smoothing_and_coord_transform
    smoothed_map = mpi.mpi_smoothing(input_map, fwhm, map_dist)
  File "//anaconda/envs/py36/lib/python3.6/site-packages/pysm3-3.1.dev270-py3.6.egg/pysm/mpi.py", line 132, in mpi_smoothing
    map_dist.libsharp_grid,
AttributeError: 'MapDistribution' object has no attribute 'libsharp_grid'

**Comment by zonca** [comment]
do you have `mpi4py`?

**Comment by zonca** [comment]
also can you run the unit tests of `pysm` and `mapsims` on your machine? `python setup.py test -V`

**Comment by stevekchoi** [comment]
I just installed mpi4py and passed all things on pysm (50 passed 4 skipped), and failed a bunch on mapsims:

=============================================== short test summary info ===============================================
FAILED mapsims/tests/test_runner.py::test_from_config - ModuleNotFoundError: No module named 'libsharp.libsharp_mpi'
FAILED mapsims/tests/test_runner.py::test_from_classes - ModuleNotFoundError: No module named 'libsharp.libsharp_mpi'
FAILED mapsims/tests/test_runner_custominstrument.py::test_from_classes_custominstrument - ModuleNotFoundError: No m...
FAILED mapsims/tests/test_runner_v02.py::test_from_config_v02 - ModuleNotFoundError: No module named 'libsharp.libsh...
FAILED docs/usage.rst
============================================ 5 failed, 16 passed in 22.72s ============================================

**Comment by zonca** [comment]
I reproduced your error, it was due to `mpi4py` missing.
what is the error on `mapsims_run`?

**Comment by zonca** [comment]
did you install `libsharp` as the instructions here? https://pysm3.readthedocs.io/en/latest/#libsharp

**Comment by stevekchoi** [comment]
Ah that's it... I missed that and installed it with github (from having installed libsharp before). I reinstalled it with conda and mapsims runs fine. Thank you very much.

**Comment by zonca** [comment]
excellent!
