### ISSUE TITLE
Import error after installing

### ISSUE THREAD

**Issue by msyriac** [simonsobs/mapsims#63]
I'm getting the following error when importing the installed package:
```
>>> import mapsims
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/r/rbond/msyriac/.local/lib/python3.6/site-packages/mapsims/__init__.py", line 7, in <module>
    from .channel_utils import Channel, parse_channels
  File "/home/r/rbond/msyriac/.local/lib/python3.6/site-packages/mapsims/channel_utils.py", line 9, in <module>
    from .utils import DEFAULT_INSTRUMENT_PARAMETERS
ImportError: cannot import name 'DEFAULT_INSTRUMENT_PARAMETERS'

```

**Comment by zonca** [comment]
Saw that before, it is when you have pieces of the previous version hanging
around.
Make sure you delete the build folder and the package folder in
site-packages

**Comment by msyriac** [comment]
Yep, that helped, thanks.
